{{- range $name, $app := .Values.apps }}
{{- if $app.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $app.project | default "default" }}
  source:
    repoURL: {{ $app.source.repoURL }}
    targetRevision: {{ $app.source.targetRevision }}
    path: {{ $app.source.path }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $app.namespace }}
  syncPolicy:
    {{- toYaml $app.syncPolicy | nindent 4 }}
{{- end }}
{{- end }}
