apiVersion: v2
name: clikhouse-wrapper
description: Wrapper chart for Clickhouse
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: clickstack
    version: 1.1.0
    repository: https://hyperdxio.github.io/helm-charts
