# App of Apps configuration
apps:
  helm:
    grafana:
      enabled: true
      name: grafana
      namespace: monitoring
      project: default
      source:
        repoURL: https://github.com/Kim007dus/homelab.git
        path: k3s/charts/grafana
        targetRevision: HEAD
    prometheus:
      enabled: true
      name: prometheus
      namespace: monitoring
      project: default
      source:
        repoURL: https://github.com/Kim007dus/homelab.git
        path: k3s/charts/prometheus
        targetRevision: HEAD
      syncPolicy:        
        syncOptions:
          - ServerSideApply=true  # Required for large CRDs in kube-prometheus-stack
      

