# App of Apps configuration
apps:
  grafana:
    enabled: true
    name: grafana
    namespace: dashboards
    source:
      # Point to YOUR git repo
      repoURL: https://github.com/Kim007dus/homelab.git
      # Point to the local wrapper chart folder
      path: k3s/charts/grafana
      targetRevision: HEAD

  prometheus:
    enabled: true
    name: prometheus
    namespace: metrics
    source:
      repoURL: https://github.com/Kim007dus/homelab.git
      path: k3s/charts/prometheus
      targetRevision: HEAD

