# App of Apps configuration
apps:  
  grafana:
    enabled: true
    name: grafana
    namespace: monitoring
    project: default
    source:
      repoURL: https://github.com/Kim007dus/homelab.git
      path: k3s/charts/grafana
      targetRevision: HEAD
  prometheus:
    enabled: true
    name: prometheus
    namespace: monitoring
    project: default
    source:
      repoURL: https://github.com/Kim007dus/homelab.git
      path: k3s/charts/prometheus
      targetRevision: HEAD
  clickhouse:
    enabled: true
    name: clickhouse
    namespace: databases
    project: default
    source:
      repoURL: https://github.com/Kim007dus/homelab.git
      path: k3s/charts/clickhouse
      targetRevision: HEAD