# App of Apps configuration
# Define all your applications here.
# An AppProject and Application will be created for each entry.
apps:
  grafana:
    enabled: true
    name: grafana
    namespace: dashboards
    source:
      repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: "10.4.3" 
    values:
      - "k3s/apps/grafana/values.yaml"

  prometheus:
    enabled: true
    name: prometheus
    namespace: metrics
    source:
      repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: "80.10.0" 
    values:
      - "k3s/apps/kube-prometheus-stack/values.yaml"
      
