apiVersion: v2
name: grafana-wrapper
description: Wrapper chart for Grafana
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: grafana
    version: 10.4.3
    repository: https://grafana.github.io/helm-charts
