apiVersion: v2
name: prometheus-wrapper
description: Wrapper chart for Prometheus (kube-prometheus-stack)
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: kube-prometheus-stack
    version: 80.10.0
    repository: https://prometheus-community.github.io/helm-charts
