# Values for the kube-prometheus-stack child chart
kube-prometheus-stack:
  fullnameOverride: prometheus
  grafana:
    enabled: false # We are deploying Grafana separately
  alertmanager:
    enabled: true
  prometheus:
    prometheusSpec:
      retention: 7d
    ingress:
      enabled: true
      hosts:
        - prometheus.homelab.local
